[package]
name = "factorio-circuit-networks"
version = "0.0.1"
edition = "2021"

[dependencies]
factorio-blueprint = { git = "https://github.com/coriolinus/factorio-blueprint" }
noisy_float = "0.1" # We need this lower version to interact with 'factorio-blueprint'
