# This Makefile was generated by Nix.
# To make changes edit the `jobs.nix` file.

main: help

all: build-all build-compiler build-inspector check-all check-git install-all install-compiler install-inspector install-python lint-all lint-clippy-compiler lint-clippy-inspector lint-fmt-compiler lint-fmt-inspector sym-install-all sym-install-compiler sym-install-inspector sym-install-python test-all test-compiler test-inspector update-scripts

help:
	@echo "usage: make <task>"
	@echo ""
	@echo "Available Tasks:"
	@echo -e '	build-all'
	@echo -e '	build-compiler'
	@echo -e '	build-inspector'
	@echo -e '	check-all'
	@echo -e '	check-git'
	@echo -e '	install-all'
	@echo -e '	install-compiler'
	@echo -e '	install-inspector'
	@echo -e '	install-python'
	@echo -e '	lint-all'
	@echo -e '	lint-clippy-compiler'
	@echo -e '	lint-clippy-inspector'
	@echo -e '	lint-fmt-compiler'
	@echo -e '	lint-fmt-inspector'
	@echo -e '	sym-install-all'
	@echo -e '	sym-install-compiler'
	@echo -e '	sym-install-inspector'
	@echo -e '	sym-install-python'
	@echo -e '	test-all'
	@echo -e '	test-compiler'
	@echo -e '	test-inspector'
	@echo -e '	update-scripts'
	@echo -e "\nUse 'make help' command to show this list."
	

build-all: build-compiler build-inspector



build-compiler: 
	cargo build --release --manifest-path "./chef-compiler/Cargo.toml"
	mkdir -p ./bin
	cp ./chef-compiler/target/release/chef ./bin/chef
	


build-inspector: 
	cargo build --release --manifest-path "./chef-inspector/Cargo.toml"
	mkdir -p ./bin
	cp ./chef-inspector/target/release/chef-inspector ./bin/chef-inspector
	


check-all: check-git lint-all



check-git: 
	git diff --quiet \
	    || { echo -e "\nPlease commit your changes."; exit 1; }
	


install-all: install-compiler install-inspector install-python



install-compiler: build-compiler
	cp -v ./bin/chef /usr/local/bin/chef
	


install-inspector: build-inspector
	cp -v ./bin/chef-inspector /usr/local/bin/chef-inspector
	


install-python: 
	pip install -e ./chef-python


lint-all: lint-fmt-compiler lint-fmt-inspector lint-clippy-compiler lint-clippy-inspector



lint-clippy-compiler: 
	cargo clippy --manifest-path "./chef-compiler/Cargo.toml" -- --deny warnings 2> /dev/null \
	    || echo -e "\nClippy is angry in 'chef-compiler'." \
	    || exit 1
	


lint-clippy-inspector: 
	cargo clippy --manifest-path "./chef-inspector/Cargo.toml" -- --deny warnings 2> /dev/null \
	    || echo -e "\nClippy is angry in 'chef-inspector'." \
	    || exit 1
	


lint-fmt-compiler: 
	cargo fmt --check --manifest-path "./chef-compiler/Cargo.toml" \
	    || echo -e "\nPlease format your files in 'chef-compiler'." \
	    || exit 1
	


lint-fmt-inspector: 
	cargo fmt --check --manifest-path "./chef-inspector/Cargo.toml" \
	    || echo -e "\nPlease format your files in 'chef-inspector'." \
	    || exit 1
	


sym-install-all: sym-install-compiler sym-install-inspector sym-install-python



sym-install-compiler: build-compiler
	ln -sv ./bin/chef /usr/local/bin/chef
	


sym-install-inspector: build-inspector
	ln -sv ./bin/chef-inspector /usr/local/bin/chef-inspector
	


sym-install-python: 
	pip sym-install -e ./chef-python


test-all: test-compiler test-inspector



test-compiler: 
	cargo test --manifest-path "./chef-compiler/Cargo.toml"
	


test-inspector: 
	cargo test --manifest-path "./chef-inspector/Cargo.toml"
	


update-scripts: 
	nix run .#gen-scripts
