# This Makefile was generated by Nix.
# To make changes edit the `jobs.nix` file.

main: help

all: build-all build-compiler build-inspector check-all check-clippy-compiler check-clippy-inspector check-fmt-compiler check-fmt-inspector install-all install-compiler install-inspector install-python test-all test-compiler test-inspector

help:
	@echo "usage: make <task>"
	@echo ""
	@echo "Available Tasks:"
	@echo -e '	build-all'
	@echo -e '	build-compiler'
	@echo -e '	build-inspector'
	@echo -e '	check-all'
	@echo -e '	check-clippy-compiler'
	@echo -e '	check-clippy-inspector'
	@echo -e '	check-fmt-compiler'
	@echo -e '	check-fmt-inspector'
	@echo -e '	install-all'
	@echo -e '	install-compiler'
	@echo -e '	install-inspector'
	@echo -e '	install-python'
	@echo -e '	test-all'
	@echo -e '	test-compiler'
	@echo -e '	test-inspector'
	@echo -e "\nUse 'make help' command to show this list."
	

build-all: build-compiler build-inspector



build-compiler: 
	echo "Building chef in chef-compiler..."
	cargo build --release --manifest-path "./chef-compiler/Cargo.toml"
	mkdir -p ./bin
	cp ./chef-compiler/target/release/chef ./bin/chef
	


build-inspector: 
	echo "Building chef-inspector in chef-inspector..."
	cargo build --release --manifest-path "./chef-inspector/Cargo.toml"
	mkdir -p ./bin
	cp ./chef-inspector/target/release/chef-inspector ./bin/chef-inspector
	


check-all: check-fmt-compiler check-fmt-inspector check-clippy-compiler check-clippy-inspector



check-clippy-compiler: 
	echo "Linting chef-compiler..."
	cargo clippy --manifest-path "./chef-compiler/Cargo.toml" -- --deny warnings 2> /dev/null \
	    || echo -e "\nClippy is angry in 'chef-compiler'." \
	    || exit 1
	


check-clippy-inspector: 
	echo "Linting chef-inspector..."
	cargo clippy --manifest-path "./chef-inspector/Cargo.toml" -- --deny warnings 2> /dev/null \
	    || echo -e "\nClippy is angry in 'chef-inspector'." \
	    || exit 1
	


check-fmt-compiler: 
	echo "Checking formatting for chef-compiler..."
	cargo fmt --check --manifest-path "./chef-compiler/Cargo.toml" \
	    || echo -e "\nPlease format your files in 'chef-compiler'." \
	    || exit 1
	


check-fmt-inspector: 
	echo "Checking formatting for chef-inspector..."
	cargo fmt --check --manifest-path "./chef-inspector/Cargo.toml" \
	    || echo -e "\nPlease format your files in 'chef-inspector'." \
	    || exit 1
	


install-all: install-compiler install-inspector install-python



install-compiler: build-compiler
	echo "Installing chef..."
	ln -s ./bin/chef /usr/local/bin/chef
	


install-inspector: build-inspector
	echo "Installing chef-inspector..."
	ln -s ./bin/chef-inspector /usr/local/bin/chef-inspector
	


install-python: 
	pip install -e ./chef-python


test-all: test-compiler test-inspector



test-compiler: 
	echo "Testing chef-compiler..."
	cargo test --manifest-path "./chef-compiler/Cargo.toml"
	


test-inspector: 
	echo "Testing chef-inspector..."
	cargo test --manifest-path "./chef-inspector/Cargo.toml"
	
