[package]
name = "chef-inspector"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"]}
eframe = { version = "0.28.1" }
factorio-blueprint = { git = "https://github.com/coriolinus/factorio-blueprint" }
