#!/bin/sh

compiler="chef-lang"
inspector="chef-inspector"

cargo fmt --check --manifest-path $compiler/Cargo.toml || {
    echo -e "\nPlease format your files."
    exit 1
}

cargo fmt --check --manifest-path $inspector/Cargo.toml|| {
    echo -e "\nPlease format your files."
    exit 1
}
