#!/bin/sh
cargo fmt --check --manifest-path chef-lang/Cargo.toml || {
    echo -e "\nPlease format your files."
    exit 1
}

cargo fmt --check --manifest-path chef-inspector/Cargo.toml || {
    echo -e "\nPlease format your files."
    exit 1
}
