#!/bin/sh

manifest="chef-lang/Cargo.toml"

echo -n "Checking format... "

cargo fmt --manifest-path "$manifest" --check 2> /dev/null  || {
    echo -e "\nPlease format your code."
    exit 1
}

echo "PASSED"

echo -n "Running clippy... "

cargo clippy --manifest-path "$manifest" -- --deny warnings 2> /dev/null || {
    echo -e "\nClippy is angry."
    exit 1
}

echo "PASSED"

echo -n "Running tests... "

make test-lang > /dev/null 2>&1 || {
    echo -e "\nSome cargo tests have failed"
    exit 1
}

echo "PASSED"

echo -n "Compiling python examples... "

make test-python > /dev/null 2>&1 || {
    echo -e "\nFailed to compile some python scipts."
    exit 1
}

echo "PASSED"

echo -n "Building with nix..."

nix build . > /dev/null 2>&1 || {
    echo -e "\nFailed to build with nix."
    exit 1
}
rm result

echo "PASSED"

echo ""
