name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -v --manifest-path chef/Cargo.toml
    - name: Run tests
      run: cargo test -v --manifest-path chef/Cargo.toml

  clippy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
          with:
              components: clippy
        - name: run clippy
          run: cargo clippy --manifest-path chef/Cargo.toml
