name: Check chef-lang

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build -v --manifest-path chef-lang/Cargo.toml
    - name: Run language tests
      run: cargo test -v --manifest-path chef-lang/Cargo.toml
    - uses: actions/setup-python@v4
      with:
          python-version: '3.10' 
    - name: Run python module tests
      run: PYTHONPATH="$(pwd)/chef-python/src" python ./chef-python/test.py

  clippy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
          with:
              components: clippy
        - name: run clippy
          run: cargo clippy --manifest-path chef-lang/Cargo.toml -- --deny warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
          with:
              components: rustfmt
        - name: run rustfmt
          run: cargo fmt --manifest-path chef-lang/Cargo.toml --check
